# Generated by Django 4.1.6 on 2023-02-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentapplication',
            old_name='secoundname',
            new_name='secound_name',
        ),
    ]
