# Generated by Django 4.1.6 on 2023-02-04 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapplication', '0002_rename_secoundname_studentapplication_secound_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='secound_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapplication.department'),
        ),
    ]
