# Generated by Django 4.1.6 on 2023-02-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapplication', '0003_department_alter_studentapplication_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=50, null=True),
        ),
    ]
