# Generated by Django 4.1.6 on 2023-02-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapplication', '0004_studentapplication_shirt_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10),
        ),
    ]
