# Generated by Django 4.1.6 on 2023-02-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapplication', '0005_studentapplication_medal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUserProfile',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
            ],
        ),
    ]
