# Generated by Django 4.1.6 on 2023-02-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapplication', '0006_createuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuserprofile',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name="person's first name"),
        ),
    ]
